=Add Support for Halting and Resuming Capp
dana-team/container-app-operator pull request #73
Opened 2023-09-03 08:47 UTC by fran2810

- Introduced functionality to halt Capp by deleting its ksvc (Knative Service).
- Implemented the capability to resume Capp by creating the ksvc.
- Incorporated relevant events and logs for tracing these actions.
- Added end-to-end tests to validate the new feature's integrity.
- Conducted code cleanup for better maintainability.
- Enhanced single responsibility principle in various components.

2023-09-11 08:22 UTC, omerbd21 requested changes

2023-09-11 08:22 UTC, omerbd21 commented on internals/utils/status/application_links.go
> +		applicationLinks.Site = strings.Split(console, ".")[2]
explain why the 3 part of the array is needed here

2023-09-11 08:22 UTC, omerbd21 commented on internals/utils/status/application_links.go
> +	openshiftConsoleKey := types.NamespacedName{Namespace: "openshift-console", Name: "console"}
why not consts?

2023-09-11 08:22 UTC, omerbd21 commented on internals/utils/status/capp.go
> +func CreateEnabledStatus(enabledStatus *rcsv1alpha1.EnabledStatus, enabledFromSpec bool) {
if all the enabled functions will be changed, this will also be changed

2023-09-11 08:22 UTC, omerbd21 commented on internals/utils/status/knative.go
> +		Limit:         100,
why not const

2023-09-12 14:24 UTC, fran2810 commented on api/v1alpha1/capp_types.go
> +	Enabled bool `json:"enabled,omitempty"`
Seems to me  more professional, and I think the word disabled or enabled indicates desired state not a status. For my taste when a clients create a manifests and want it to just hold the configuration and not run his application, disabled for me describe this scenario.

2023-09-12 14:26 UTC, fran2810 commented on api/v1alpha1/capp_types.go
> +	CurrentState bool `json:"currentState,omitempty"`
i agree ill wait with this when we resolve the running/enabled issue

2023-09-12 14:33 UTC, fran2810 commented on cmd/main.go
> +		Client:        mgr.GetClient(),
That's the acceptable indentation when beautify my code ctrl+alt+l

2023-09-12 14:34 UTC, fran2810 commented on README.md
accident

2023-09-12 14:36 UTC, fran2810 commented on config/manager/kustomization.yaml
> +  newTag: latest
mistake ill fix it

2023-09-12 14:40 UTC, fran2810 commented on internals/controllers/capp_controller.go
> +	Scheme        *runtime.Scheme
default indentation of goland

2023-09-14 11:37 UTC, omerbd21 approved these changes
/lgtm

2023-09-14 11:57 UTC, mzeevi commented
/hold until we fix the e2e tests

2023-12-24 19:13 UTC, mzeevi commented
Fix conflicts and resubmit @fran2810

2023-12-25 19:52 UTC, fran2810 commented
reopening in a new pr

2023-12-25 19:52 UTC, closed without merging