Test e2e ginkgo
dana-team/container-app-operator pull request #76
Opened 2023-09-14 18:07 UTC by fran2810

- Implemented e2e tests using the Ginkgo framework.
- Introduced utility and compose functions to streamline future test development.

2023-09-14 19:37 UTC, mzeevi commented on test/k8s_tests/e2e_test.go
> +		}, 16*time.Second, 2*time.Second).Should(Equal("rps"), "Should fetch capp")
Maybe move the `16*time.Second`, `2*time.Second`  to be consts that can be re-used?

2023-09-14 19:37 UTC, mzeevi commented on test/k8s_tests/e2e_test.go
> +})
Add a blank space between `By` stanzas for better readability.

2023-09-14 19:40 UTC, mzeevi commented on test/k8s_tests/mocks/base.go
> +									Image:     "sahar2339/example-python-app:v1-flask",
Change image to use `quay.io/danateamorg/example-python-app:v1-flask` or alternatively upload it to `ghcr.io` in this repository and use that instead

2023-09-14 19:41 UTC, mzeevi commented on test/k8s_tests/mocks/base.go
> +	NsName = "capp-e2e-tests"
Shouldn't it be `nsName`?

2023-09-14 19:42 UTC, mzeevi commented on test/k8s_tests/test_suite.go
> +	K8sClient client.Client
is the capital letter here on purpose?

2023-09-14 19:43 UTC, mzeevi commented on test/k8s_tests/utils/capp_adapter.go
> +func generateRandomString(length int) string {
Add a short comment above the function

2023-09-14 19:44 UTC, mzeevi commented on test/k8s_tests/utils/capp_adapter.go
> +			Namespace: "test-ns",
Are these values hard-coded on purpose?

2023-09-14 19:45 UTC, mzeevi commented on test/k8s_tests/utils/resources_adpater.go
> +func DoesResourceExists(k8sClient client.Client, obj client.Object) bool {
`DoesResourceExist`, not `...Exists`

2023-09-14 19:45 UTC, mzeevi requested changes
Looks good overall but I have some questions

2023-09-14 19:47 UTC, fran2810 commented on test/k8s_tests/mocks/base.go
> +	NsName = "capp-e2e-tests"
It won't be exposed

2023-09-14 19:48 UTC, fran2810 commented on test/k8s_tests/test_suite.go
> +	K8sClient client.Client
No I'll change it

2023-09-14 19:49 UTC, fran2810 commented on test/k8s_tests/utils/capp_adapter.go
> +			Namespace: "test-ns",
No I'll change it

2023-10-31 07:37 UTC, mzeevi commented
The CI still fails, think it's more related to the CI and not the tests

2023-12-13 10:52 UTC, mzeevi approved these changes

2023-12-13 10:52 UTC, mzeevi commented
/lgtm
/approve

2023-12-13 10:52 UTC, merged